// Example sentences, generated once and stored here on 2026-08-27.
// Static on purpose: a sentence for a word never changes, so there is no
// reason to ask for it again at runtime. Words added to the sheet later fall
// back to the sheet's own example until this file is regenerated.
var SENTENCES = {
"abduct-1": "In the film, robbers try to abduct the princess and carry her off in a van.",
"absurd-1": "Wearing swimming goggles to eat spaghetti is an absurd idea, though it made us laugh.",
"abundance-1": "After the rain, our garden had an abundance of snails, far more than we could count.",
"acquaint-1": "Our teacher spent Monday helping us acquaint ourselves with the new library computers.",
"adequate-1": "One water bottle each was adequate for our short hike, so we left the rest home.",
"adhere-1": "Swimmers must adhere to the pool rules, so nobody runs or dives in the shallow end.",
"adhere-2": "Wet leaves adhere to my boots so tightly that I have to scrape them off.",
"adjacent-1": "My locker is adjacent to Sam's, so we chat every morning while grabbing our books.",
"adversary-1": "My chess adversary smiled across the board and moved her queen to trap my king.",
"affinity-1": "My sister has a natural affinity for animals, and even shy cats come to her.",
"allegation-1": "The allegation that Mia copied her homework faded once nobody could show any real proof.",
"alluring-1": "The smell of warm cookies was so alluring that I followed it straight to the kitchen.",
"aloof-1": "The new boy stayed aloof at recess, watching our games from a bench without speaking.",
"appease-1": "Dad appeased my crying little sister by handing her the toy she had been begging for.",
"appreciative-1": "Grandma was appreciative of the birthday card I drew, and she hugged me twice.",
"appreciative-2": "The whole class was appreciative when our teacher stayed late to help us finish the model.",
"apprehensive-1": "I felt apprehensive before the spelling bee, sure I would forget every word on stage.",
"apt-1": "\"Muddy Monster\" was an apt nickname for my dog after his run through the swamp.",
"apt-2": "Such an apt learner, she understood the new card game after watching just one round.",
"aptitude-1": "Wesley has a real aptitude for drawing horses, even though nobody ever taught him how.",
"architecture-1": "On our trip we studied the architecture of tall churches with pointed towers and colored windows.",
"arduous-1": "Shoveling the whole driveway after the storm was arduous work, and my arms ached for hours.",
"artefact-1": "The digger found an ancient artefact, a broken bowl used by people thousands of years ago.",
"artefact-2": "Diggers found a stone artefact left behind by people who lived here thousands of years ago.",
"assiduous-1": "My assiduous brother practises piano an hour every day, even on holidays and weekends.",
"assortment-1": "Grandpa's tin held an assortment of buttons, each a different colour, shape, and size.",
"asunder-1": "The wind ripped our old kite asunder, scattering paper and sticks across the field.",
"audacity-1": "My little brother had the audacity to call Grandma's cooking gross right at the dinner table.",
"audacity-2": "With great audacity, she dived from the highest board while the whole swim team watched.",
"audition-1": "At the audition, I sang one short song and hoped to be picked for the choir.",
"audition-2": "At the audition, Emma sang one short song and hoped the band would choose her.",
"barren-1": "Nothing grew on the barren hillside, just dry dust, cracked ground, and a few stones.",
"bemoan-1": "My brother began to bemoan the rain that washed out his birthday baseball game.",
"brusque-1": "The bus driver's brusque \"Sit down!\" made us all go quiet and stop laughing.",
"catastrophe-1": "The earthquake was a catastrophe that flattened houses and left many families with nothing.",
"citizen-1": "My dad became a citizen of Australia last year and proudly received his new passport.",
"citizen-2": "After living in Spain for ten years, my uncle became a citizen of that country.",
"collide-1": "Watch out, or your bike will collide with the fence at the bottom of the hill.",
"committee-1": "Six students formed a committee to plan the sports day for the whole school.",
"committee-2": "Six pupils formed a committee to plan the sports day for the whole school.",
"complemented-1": "The warm soup complemented the crusty bread perfectly, making our cold winter lunch feel complete.",
"complemented-2": "The warm gravy complemented the roast potatoes perfectly, making the whole dinner taste better.",
"compliment-1": "My coach gave me a compliment about my throwing, and I smiled the whole way home.",
"component-1": "Each component of the model plane came in its own little bag with a number.",
"composed-1": "Even when her cake fell over, Mia stayed composed and quietly started again.",
"comrade-1": "Every player hugged his comrade after the long, muddy match they had fought together.",
"confer-1": "The teachers stepped outside to confer before choosing who would carry the flag.",
"contempt-1": "The cat stared at her cheap new food with total contempt and walked away.",
"contradict-1": "My little brother loves to contradict me, saying black whenever I say white.",
"controversy-1": "The referee's final whistle caused a huge controversy, with parents shouting at each other for days.",
"convenient-1": "A pocket on my bag is convenient for keeping my bus pass handy.",
"cryptic-1": "Grandpa gave a cryptic smile and said the treasure was closer than we thought.",
"curiosity-1": "Pure curiosity kept Sam reading about volcanoes long after his bedtime light went off.",
"debris-1": "After the tree fell, we swept up branches, leaves and other debris from the yard.",
"decipher-1": "We tried to decipher the faded map, but the ink had smudged into blobs.",
"deduce-1": "From the crumbs on his shirt, Mum could deduce who had eaten the last cookie.",
"destitute-1": "The flood left many families destitute, with no food, clothes or dry beds.",
"diligence-1": "With quiet diligence, Ben practiced piano every single morning before school for a year.",
"disastrous-1": "Our first game was disastrous; we lost twelve to nothing and our goalie broke his wrist.",
"discrepancy-1": "The teacher spotted a discrepancy between my answer and the one in the marking book.",
"distraction-1": "My little brother's drumming was such a distraction that I read the same page twice.",
"disused-1": "Swallows nest in the disused barn where no farmer has stored hay for years.",
"divulge-1": "Please don't divulge my birthday surprise to Mum before Saturday morning.",
"eagerness-1": "The puppy's eagerness for a walk made him spin circles by the front door.",
"earnest-1": "In an earnest voice, Tom said he truly meant to pay back every coin.",
"elected-1": "After counting all the votes, our class elected Priya as school council leader.",
"eloquence-1": "His speech about saving the pond had such eloquence that the head teacher agreed.",
"embroil-1": "Please don't embroil me in your argument about whose turn it is to walk the dog.",
"emulate-1": "Ben wants to emulate his hero, so he practises free throws every single evening.",
"enamour-1": "My sister was so enamoured of the fluffy puppy that she refused to leave the shelter.",
"endeavour-1": "Building the treehouse alone was a huge endeavour that took Jack all summer.",
"entice-1": "We used seeds to entice the shy robin onto the windowsill.",
"evacuate-1": "When the river rose, police helped everyone evacuate the flooded village before dark.",
"evident-1": "The muddy paw prints on my bed made it evident that the dog had climbed up.",
"evolve-1": "Our school garden club slowly evolved into a big team that now runs the farmers market.",
"exaggerate-1": "My brother exaggerates every game, saying he scored twenty goals when he really scored two.",
"existence-1": "My little sister still believes in the existence of fairies living under the garden shed.",
"existence-2": "Nobody has ever proved the existence of dragons, though many old stories describe them.",
"exquisite-1": "Grandma's exquisite lace tablecloth had tiny flowers stitched so perfectly that everyone leaned in to look.",
"fabricate-1": "Rather than admit he forgot his homework, Tom fabricated a wild story about a hungry dog.",
"fathom-1": "No matter how long I stared, I could not fathom the last puzzle question.",
"feign-1": "Tom tried to feign a stomach ache so he could skip the spelling test.",
"flippant-1": "When Grandma spoke about the war, his flippant joke made the whole table go quiet.",
"forecast-1": "The weather forecast said snow tonight, so we left our sleds by the door.",
"foreign-1": "The coins in Dad's jar are foreign, collected from countries he visited before I was born.",
"forthcoming-1": "Our teacher reminded us about the forthcoming sports day, which starts early next Friday morning.",
"fortuitous-1": "It was fortuitous that Mom drove past just as the rain began soaking my bag.",
"frugal-1": "My frugal grandma saves every coin, cuts coupons, and never wastes a single slice of bread.",
"gluttonous-1": "Our gluttonous puppy ate his whole dinner, then tried to eat the cat's food too.",
"gratitude-1": "I felt real gratitude toward the neighbor who found my lost dog and walked him home.",
"gratitude-2": "The rescued puppy showed its gratitude by licking the firefighter's hand again and again.",
"gregarious-1": "My gregarious cousin made six new friends before lunchtime on her very first camp day.",
"grotesque-1": "The mask had a grotesque grin with swollen lips and one bulging eye, and I stepped back.",
"grudge-1": "My sister still holds a grudge because I broke her favourite mug two summers ago.",
"guarantee-1": "The shop gave us a guarantee that they would replace the tent if it leaked.",
"guarded-1": "Dad was guarded about our holiday plans, saying only that we would need warm coats.",
"hapless-1": "The hapless puppy got soaked by rain, stung by a bee, then chased by geese.",
"harmonious-1": "After the argument, our team became harmonious again and everyone passed the ball happily.",
"hindrance-1": "My long scarf was a hindrance while climbing, catching on every branch and slowing me down.",
"idyllic-1": "The farm looked idyllic, with lambs in green fields and sunlight on the little pond.",
"immaculate-1": "Gran's kitchen is immaculate, with every spoon shining and not one crumb on the floor.",
"implore-1": "I had to implore my brother, almost in tears, to stop teasing the frightened cat.",
"inaudible-1": "Her whisper was inaudible, so I leaned closer and asked her to repeat it.",
"inkling-1": "I had no inkling that Mum had hidden a puppy in the garage until it barked.",
"insolent-1": "The insolent boy rolled his eyes and told the coach to mind his own business.",
"insomnia-1": "Excited about the field trip, I had insomnia and stared at the ceiling until morning.",
"intangible-1": "Friendship is intangible, since you cannot hold it, weigh it, or put it in a box.",
"invaluable-1": "My old bike pump was invaluable on the camping trip, and I would never sell it.",
"investigate-1": "We decided to investigate the strange scratching noise by shining a torch under the shed.",
"jargon-1": "Dad's work emails are full of jargon that means nothing to anyone outside his office.",
"judicious-1": "A judicious captain saves her fastest runner for the final leg of the relay.",
"latent-1": "The seeds looked dead, but latent life inside them burst out after the spring rain.",
"lenient-1": "Grandma is lenient about bedtime, so we watch films long after Mum would say stop.",
"lethargy-1": "The hot afternoon filled the dog with lethargy, and he barely lifted his head.",
"magnitude-1": "Standing at the base, we finally understood the magnitude of the mountain above us.",
"majestic-1": "A majestic eagle spread its huge wings and glided slowly over the silent lake.",
"malign-1": "Some kids malign the new girl with made-up stories, though she has done nothing wrong.",
"melancholy-1": "A quiet melancholy filled the house on the last day of our summer holiday.",
"mesmerize-1": "The spinning snow outside the window mesmerized me, and I forgot all about my homework.",
"milestone-1": "Swimming a whole length without stopping was a huge milestone for Jack this term.",
"mitigate-1": "A thick scarf and gloves mitigate the sting of the freezing wind on your walk.",
"nourishment-1": "The puppy got all its nourishment from its mother's milk during those first few weeks.",
"obsolete-1": "Grandad's huge car phone is obsolete now that everyone carries a tiny mobile.",
"obstinate-1": "My obstinate brother would not admit he was wrong, even when Mum showed him the rules.",
"oppress-1": "In the film, cruel guards oppressed the villagers and took away every bit of their freedom.",
"orchestrate-1": "Our teacher orchestrated the whole school play, from costumes to lighting to the final bow.",
"ostentatious-1": "He gave an ostentatious wave to the crowd so everyone would notice his new trainers.",
"paraphrase-1": "Instead of copying the page, paraphrase what the article said about how volcanoes erupt.",
"peculiar-1": "Our cat has the peculiar habit of sleeping inside the empty bathtub every afternoon.",
"pilfer-1": "The cheeky squirrel pilfered a few nuts from the bird feeder each morning.",
"pioneer-1": "My grandmother was a pioneer, the first woman to fly a plane across our country.",
"placid-1": "Our old pony stays placid even when little children shout and run around her field.",
"populate-1": "Thousands of noisy seabirds populate the cliffs behind our beach every single summer.",
"prejudice-1": "He refused to play with the new boy, and that was just silly prejudice.",
"privilege-1": "Feeding the class rabbit is a privilege earned only by pupils who finish their homework.",
"procure-1": "Dad phoned six shops before he could procure the exact paint we needed for the shed.",
"proficient-1": "After swimming every weekend for two years, Mia became proficient at diving off the block.",
"prohibit-1": "School rules prohibit mobile phones in class, so mine stays in my bag.",
"prominent-1": "A prominent red barn stands out on the hill and helps us find the farm.",
"prospective-1": "Coach watched the prospective goalkeepers, hoping one would join the team next season.",
"prosperous-1": "The bakery grew prosperous, and soon the owners opened three more shops in town.",
"provoke-1": "My brother pokes my arm again and again to provoke me into shouting.",
"punctual-1": "Our coach is always punctual, so practice starts at four o'clock exactly, every single week.",
"quaint-1": "The village had quaint little shops with wooden signs and windows from a hundred years ago.",
"quench-1": "After running all afternoon in the heat, only cold lemonade could quench my burning thirst.",
"reconcile-1": "The brothers argued about the game, but they reconciled before dinner and played together again.",
"reimburse-1": "My teacher promised to reimburse me for the paint I bought for our class poster.",
"remedy-1": "Dad says a hot bath is the best remedy for sore legs after a long hike.",
"remorse-1": "She felt terrible remorse after shouting at her best friend over something so small.",
"rendition-1": "His piano rendition of the school song made everyone in the hall clap loudly.",
"reproach-1": "Mom said nothing, but the reproach in her eyes told me she saw the mess.",
"reputation-1": "Our team has a reputation for never giving up, even when losing badly.",
"reputation-2": "Our goalkeeper has a reputation for stopping penalties, so strikers get nervous facing him.",
"revolutionize-1": "The new library app will revolutionize how we borrow books, changing everything about the old system.",
"sacrificed-1": "Mum sacrificed her own new coat so I could have the boots I needed.",
"sacrificed-2": "Mum sacrificed her own slice of cake so that each child could have one.",
"scarcity-1": "Because of the scarcity of rain this summer, our garden turned brown and crispy.",
"scrutinise-1": "The judges scrutinise every science project, checking the charts and asking careful questions about our results.",
"seldom-1": "Our cat seldom comes inside, so we were shocked to find her sleeping on my bed.",
"simultaneous-1": "Our simultaneous shouts of \"Goal!\" made the whole crowd laugh, because we yelled the exact same moment.",
"sincerity-1": "He thanked us with such sincerity that we knew he truly meant every word.",
"sincerity-2": "The boy thanked us with such sincerity that we knew he really meant every word.",
"skirmish-1": "A brief skirmish broke out over the last soccer ball, but our teacher settled it quickly.",
"solitary-1": "My brother took a solitary walk to the pond, wanting no company but his own thoughts.",
"solitary-2": "He took a solitary walk to the pond, leaving his noisy brothers back at home.",
"sophisticated-1": "Our school's new robot is so sophisticated that it can sort books by itself.",
"sophisticated-2": "My cousin's robot is so sophisticated that it can climb stairs and follow spoken orders.",
"stagnate-1": "If you never read harder books, your reading skills will stagnate and stop getting better.",
"stalemate-1": "Our chess match ended in a stalemate, with neither player able to make a winning move.",
"stalemate-2": "Our chess game ended in a stalemate, since neither of us could capture anything.",
"stupendous-1": "Her stupendous catch in the last second made the whole crowd jump up and cheer.",
"suave-1": "In his neat suit and polished shoes, my uncle looked suave enough to host a show.",
"substantial-1": "Dad served me a substantial breakfast, and I could not finish even half of it.",
"succinct-1": "Instead of a long story, give me a succinct answer: who broke the window?",
"surveillance-1": "The zoo keeps the panda cubs under constant surveillance with cameras in every corner.",
"swindled-1": "The man at the fair swindled Dad, selling him a bike with no brakes.",
"tactful-1": "Being tactful, Mia praised her friend's drawing instead of mentioning the crooked, lopsided horse.",
"tedious-1": "Weeding the whole garden row by row was tedious, and my back began to ache.",
"texture-1": "The kitten's fur had a silky texture, quite unlike our dog's wiry coat.",
"thwart-1": "Heavy rain thwarted our plan to camp in the back garden on Saturday night.",
"turmoil-1": "The classroom was in turmoil when the escaped hamster ran under everybody's desks.",
"twilight-1": "Bats swooped over the field in the twilight, just before the stars appeared.",
"vapour-1": "Warm vapour rose from my soup and curled slowly toward the cold window.",
"vapour-2": "Warm vapour rose off the pool on the cold morning, hiding the swimmers from view.",
"verify-1": "Dad counted the change twice to verify that the shop had given him the right amount.",
"verify-2": "Dad phoned the coach to verify that practice really started an hour earlier today.",
"versatile-1": "My versatile teammate can play goalie, defense, or forward whenever the coach needs him.",
"vicinity-1": "Mom told us to stay in the vicinity of the tent, never far into the woods.",
"wholesome-1": "Camp felt wholesome: fresh air, real food, kind friends, and no screens for a week.",
"wretched-1": "The wretched stray dog shivered in the rain with muddy fur and no home."
};
